spring:
  profiles:
    active: develop

---
spring:
  profiles: develop

  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/siba_be_dev
    username: root
    password: 1111
    driver-class-name: org.mariadb.jdbc.Driver
    dbcp2:
      validation-query: SELECT 1

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 78555b1f568a577ea845f416369efbe4
            clientSecret: SvgIT2D8qxyARKS8zAUAXhRV6lwSp2iQ
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: POST

        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://39.117.253.166:3000/oauth2/redirect

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:org.icslab.siba/**/*.xml #*Mapper.xml이 위치한 경로
#spring.profiles.include: develop-db

server:
  port: 8080